### PR TITLE
Consume all data before emitting the `close` event

### LINKED ISSUE #799: Last frame's payload not delivered and code 1006 returned
The title may not be 100% accurate, I apologize for that but it's not too clear to me what's happening...
### Versions

I can say for sure that this happens with version 1.1.1 but not with 0.4.32.

**Edit:** It doesn't work with version 0.8.1 either. The only difference with respect to 1.1.1 is that the close event code is still 1000.
### Client code

The client code is not really important, you can use the basic:

``` js
var WebSocket = require('ws');
var ws = new WebSocket(process.argv[2]);

ws.on('message', function (data, flags) {
    console.log('>', data);
});

ws.on('close', function (code, message) {
    console.error('#', code, message);
});
```

or even [`wscat`](https://github.com/websockets/wscat), what really matter is the `ws` version.
### How to reproduce

This behavior has been observed with the Google Chrome's Remote Debugging Protocol WebSocket; (cyrus-and/chrome-remote-interface#39).

Here are the step to reproduce this issue:
1. start a new Chrome session with `--remote-debugging-port=9222`;
2. fetch a list of the currently open tabs:
   
   ```
   $ curl http://localhost:9222/json
   [ {
      "description": "",
      "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/952808E7-26BC-470B-B1DF-B61519786481",
      "faviconUrl": "https://www.google.it/favicon.ico",
      "id": "952808E7-26BC-470B-B1DF-B61519786481",
      "title": "New Tab",
      "type": "page",
      "url": "chrome://newtab/",
      "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/952808E7-26BC-470B-B1DF-B61519786481"
   },
   [...]
   ```
   
   Locate the new empty tab (`chrome://newtab/`) and not the WebSocket URL (in this case `ws://localhost:9222/devtools/page/952808E7-26BC-470B-B1DF-B61519786481`).

3. connect to that URL:
   
   ```
   $ wscat -c ws://localhost:9222/devtools/page/952808E7-26BC-470B-B1DF-B61519786481
   connected (press CTRL+C to quit)
   ```
4. from Chrome open the DevTools for that tab (this will close the WebSocket).
#### What happens with 1.1.1

```
connected (press CTRL+C to quit)
disconnected
```

Using a custom client we obtain the close event code 1006.

Using Wireshark we notice:
- `Sec-WebSocket-Extensions` is set to `permessage-deflate; client_max_window_bits=15` in the handshake reply;
- `Fin: True` and `Reserved: 0x04` and the payload is not human-readable in the last (and only) WebSocket frame.
#### What happens with 0.4.32

```
connected (press CTRL+C to quit)
< { "method": "Inspector.detached", "params": { "reason": "replaced_with_devtools"} }
disconnected
```

Using a custom client we obtain the close event code 1000.

Using Wireshark we notice:
- `Sec-WebSocket-Extensions` is not set in the handshake reply;
- `Fin: True` and `Reserved: 0x00` and the payload is the above JSON text in the last (and only) WebSocket frame.

### PR DESCRIPTION
**Pull request by lpinca**
This makes `Receiver.prototype.cleanup()` accept an optional callback which is called when all buffered data is consumed or an error occurs.

Using this callback we can handle cases where the parser is decompressing data and the other peer closes the underlying TCP connection. Previously when this happened the buffered data was simply discarded. Now all data should be handled correctly.

Fixes #799 and #923.

This is based and supersedes #840.

@websockets/admin this really needs to be reviewed carefully so when you have time please take a look.

### CODE REVIEW

File: lib/Receiver.js [hunk 1]
```diff
@@ -466,21 +482,28 @@ class Receiver {
...
+      this.buffers = null;
+      this.mask = null;
+
+      this.onmessage = null;
+      this.onclose = null;
+      this.onerror = null;
+      this.onping = null;
+      this.onpong = null;
+
+      if (cb) cb();
```
Comment (3rd-Eden) [inline lib/Receiver.js]: Do we want to set the `cleanupCallback` to null here as well?

File: lib/WebSocket.js [hunk 2]
```diff
@@ -214,7 +228,7 @@ class WebSocket extends EventEmitter {
     this.extensions = null;
 
     this.removeAllListeners();
-    this.on('error', function onerror () {}); // catch all errors after this
+    this.on('error', noop); // Catch all errors after this.
```
Comment (3rd-Eden) [inline lib/WebSocket.js]: Not related to this PR, but we need start doing a cleaner way of handling this. Right now valid errors might get swallowed without us knowning. Maybe something like `diagnostics`/`debug` would be more useful here so we can at least still log when these errors get swallowed.

File: lib/Receiver.js (hunk 1 above)
Comment (lpinca) [inline lib/Receiver.js]: 🔧 in 1c547cb.

File: lib/WebSocket.js (hunk 2 above)
Comment (lpinca) [inline lib/WebSocket.js]: I _think_ the only cases where an error event may be emitted here are when trying to write to a socket that has already been closed due to write operation being queued in the `Sender`. In particular.

1. https://github.com/websockets/ws/blob/549cbe11527320f123e423bb13a1b20bc1807874/lib/WebSocket.js#L266.

2. https://github.com/websockets/ws/blob/549cbe11527320f123e423bb13a1b20bc1807874/lib/WebSocket.js#L159.

Maybe we should remove all queued operations in `Sender` when `finalize` is called.
